# docker-compose.yml
version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - .:/app
      - ./static/uploads:/app/static/uploads
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
